name = "Pedestrian"
license = "MIT"
licenselink = "https://github.com/vimux/blank/blob/master/LICENSE.md"
description = "Hugo theme for Don't Walk."
homepage = ""
tags = ["yellow", "ice-cream", "ice-lolly"]
features = ["yellow"]
min_version = 0.54

[author]
  name = "Don't Walk"
  homepage = "https://dont-walk.com"
